language: php

php:
  - 5.3
  - 5.6
  
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  
script: phpunit

notifications:
  email:
    - sean@headzoo.io
